### PR TITLE
Setup Coverity Static Analysis | TEST

### PR DESCRIPTION
**Pull request by JustinASmith**
## Description

- Testing Travis CI configuration for Coverity Static Analysis scan.

### CODE REVIEW

**Comment by pranmar123** [comment]
Let me take a look into Coverity. Thanks for finding the tool.

**Comment by JustinASmith** [comment]
@pranmar123 No. It is supposed to trigger the Static Coverage report, but it is not for some reason.

**Comment by pranmar123** [comment]
> 
> 
> @pranmar123 No. It is supposed to trigger the Static Coverage report, but it is not for some reason.

I wonder if it is because it is not part of the master branch?

**Comment by JustinASmith** [comment]
> > @pranmar123 No. It is supposed to trigger the Static Coverage report, but it is not for some reason.
> 
> I wonder if it is because it is not part of the master branch?

@pranmar123 Well, it is supposed to only be triggered when you push to the 'coverity_scan' branch because it can be an expensive/lengthy scan.

**Comment by JustinASmith** [comment]
Closing for a better, easier eslint static analysis setup.

**Pull request closed without merging**
