### PR TITLE
Add fullpagespinner

### PR DESCRIPTION
**Pull request by pranmar123**
## Description

- Still a work in progress; cannot figure out how to center it in the middle of the page. I have it centered, but it is at top. Any thoughts @JustinASmith? (see image below)
hmmmm

- Also I might have another bug in the landingpage. Is this showing up like this for everyone else too?
bug

- Addresses issue #104

### CODE REVIEW

**Comment by JustinASmith** [comment]
@pranay This is how I would do it 🤞

**Comment by JustinASmith** [comment]
@pranmar123  Also, that isn't a bug. I had to delete boilerplate css in App.css which caused this. I am 99% sure at least. Commit is here 8fe077c4051f90e0d98d7743f4d6bc728b7e84f9

**Comment by JustinASmith** [comment]
@pranmar123 That can be a new issue for you to tackle haha. I would take the pieces that are needed only. The only piece needed is "App-header" css class

**Comment by JustinASmith** [comment]
@pranmar123 You can create a css file for landing component and import that css file into that component

**Comment by pranmar123** [comment]
@JustinASmith All right, I can file a new issue for that. In terms of this issue though, is it ready to be merged?

**Comment by pranmar123** [comment]
> 
> 
> I am not sure if I should of pushed to the PR for a review, but I did. This works, but you will still have to conditionally render this in App.js when network.is_loading

No, it is good that you did. I agree with those changes. That is a better way of doing it.

**Comment by JustinASmith** [comment]
@pranmar123 This isn't ready to merge yet. Look back at the issue to the link I put there. You have to conditionally render the `<FullPageSpinner/>` if network.is_loading otherwise just return the stuff returned in App.js

**Comment by JustinASmith** [comment]
> @pranmar123 This isn't ready to merge yet. Look back at the issue to the link I put there. You have to conditionally render the `<FullPageSpinner/>` if network.is_loading otherwise just return the stuff returned in App.js



> > I am not sure if I should of pushed to the PR for a review, but I did. This works, but you will still have to conditionally render this in App.js when network.is_loading
> 
> No, it is good that you did. I agree with those changes. That is a better way of doing it. @JustinASmith

https://gist.github.com/JustinASmith/00ad9e25b0d7815c6f7399cea5a6e5e9

**Comment by JustinASmith** [comment]
> @JustinASmith All right, I can file a new issue for that. In terms of this issue though, is it ready to be merged?

https://gist.github.com/JustinASmith/00ad9e25b0d7815c6f7399cea5a6e5e9

**Comment by pranmar123** [comment]
> 
> 
> > @JustinASmith All right, I can file a new issue for that. In terms of this issue though, is it ready to be merged?
> 
> https://gist.github.com/JustinASmith/00ad9e25b0d7815c6f7399cea5a6e5e9

I can't find that code in the App.js version of my file. Is that what I need to add along with importing the fullpagespinner? @JustinASmith

**Comment by JustinASmith** [comment]
> > > @JustinASmith All right, I can file a new issue for that. In terms of this issue though, is it ready to be merged?
> > 
> > 
> > https://gist.github.com/JustinASmith/00ad9e25b0d7815c6f7399cea5a6e5e9
> 
> I can't find that code in the App.js version of my file. Is that what I need to add along with importing the fullpagespinner? @JustinASmith

@pranmar123 The code is on master. I have it referenced first but in the gist link I have attached after is just the outer div of what I referenced in App.js. You have to do what I did in the gist. I just put "..." so I didn't have to write out all the routes, etc.

**Comment by JustinASmith** [comment]
> > > @JustinASmith All right, I can file a new issue for that. In terms of this issue though, is it ready to be merged?
> > 
> > 
> > https://gist.github.com/JustinASmith/00ad9e25b0d7815c6f7399cea5a6e5e9
> 
> I can't find that code in the App.js version of my file. Is that what I need to add along with importing the fullpagespinner? @JustinASmith

@pranmar123 But yes you would have to import fullpagespinner and then do the conditional of is_loading. All this is happening inside of client/src/App.js

**Comment by JustinASmith** [comment]
@pranmar123 Here is a screen shot of what you'd need to do along with importing the component. I forgot we would need to render the navigation as well.

image

**Comment by JustinASmith** [comment]
@pranmar123  What is the status of this?

**Comment by pranmar123** [comment]
Updated code to address @JustinASmith 's comments. Thanks for the help! :+1:

**Pull request merged**
