### PR TITLE
Redux authentication, redirecting, and state management

### PR DESCRIPTION
**Pull request by JustinASmith**
## Description

- Fixes user login/registration by:
1. Managing state of application using _Redux_.
2. Redirecting from redux action creators instead of component level.
3. Using custom redux middlware function to handle redirects.
4. Using a custom react hook to detect authentication status and passing status to components that need that information _(Private Routes)_.

- Addresses issue #99

### CODE REVIEW

**Comment by pranmar123** [comment]
Looks good to me! Thanks for the in-depth PR description.

**Comment by JustinASmith** [comment]
This PR fixes the bug, but all other features of create, update, and getting chirps is unavailable. This is due to the new state management. I will fix this ASAP and create a new PR. Can @pranmar123 create a new issue for this?

**Comment by JustinASmith** [comment]
@pranmar123 I was a little vague. Because I implemented Redux as our state management instead of component level, the feed page, chirp component, etc do not have access to the JWT token. I will have to extract the API request into action creators (actions/index.js) and use the set token inside the redux store where needed.

**Comment by pranmar123** [comment]
> 
> 
> This PR fixes the bug, but all other features of create, update, and getting chirps is unavailable. This is due to the new state management. I will fix this ASAP and create a new PR. Can @pranmar123 create a new issue for this?

Creating the new issue now

**Comment by pranmar123** [comment]
> 
> 
> > This PR fixes the bug, but all other features of create, update, and getting chirps is unavailable. This is due to the new state management. I will fix this ASAP and create a new PR. Can @pranmar123 create a new issue for this?
> 
> Creating the new issue now

Issue created. See #103 . Bug labeled set as critical.

**Comment by JustinASmith** [comment]
@Keithw12 This closes #99

**Pull request merged**
