### PR TITLE
Feed design and functionality

### PR DESCRIPTION
**Pull request by JustinASmith**
## Fully functional feed page

- This fully implements the feed page and functionality, excluding like, rechirp, follow.
- Features implemented:
- - Create a chirp
- - Get all chirps
- - Delete a chirp
- - Update a Chirp

- Addresses issues #35 #36 #37 #65

### CODE REVIEW

**Comment by JustinASmith** [comment]
There will need to be improvements to this later of course. The biggest design improvement I can see is to make this page responsive to screen sizes.

**Comment by JustinASmith** [comment]
Many test cases can be written later as well.

**Comment by JustinASmith** [comment]
@Keithw12 Did you try the functionality out!?? Was all features working? (create, update, delete chirp)

**Comment by pranmar123** [comment]
Downloading the latest version and testing out the changes; so far looks so good.

**Comment by Keithw12** [comment]
> @Keithw12 Did you try the functionality out!?? Was all features working? (create, update, delete chirp)

Doesn't it need to be merged before I can pull it and test?  If not, I can't recall the command to pull a specific branch from remote

**Comment by pranmar123** [comment]
> 
> 
> > @Keithw12 Did you try the functionality out!?? Was all features working? (create, update, delete chirp)
> 
> Doesn't it need to be merged before I can pull it and test? If not, I can't recall the command to pull a specific branch from remote

To pull down this pull request, go to a new branch and do a `git pull origin feedDesign`

That command will give you his changes in this PR for you to be able to test them out on your local machine.

**Comment by JustinASmith** [comment]
@pranmar123 @Keithw12 Is the chirp text centered or left aligned for you? It is supposed to be left aligned like the picture I sent via text.

**Comment by JustinASmith** [comment]
Never mind that, I forgot to commit this file to fix that. So that should be the last of the commits for this PR. I will verify my work once more and test. If @pranmar123 @Keithw12 can check/test design/style and functionality thoroughly I will merge thereafter.

**Comment by JustinASmith** [comment]
I am 99.99% this PR is good, I will merge.

**Pull request merged**
