### PR TITLE
ESLint Reformat

### PR DESCRIPTION
**Pull request by Keithw12**
## Description

- Reformatted all code to fit ESLint formatting standards.  (Improved code readability)

Everyone now use ESLint extension in VS Code....

### CODE REVIEW

**Comment by JustinASmith** [comment]
I think this is good and all, but what ESlint configuration do you use?

**Comment by Keithw12** [comment]
> I think this is good and all, but what ESlint configuration do you use?

Default I believe.  I didn't modify the ESlint config.

**Comment by JustinASmith** [comment]
Have you tested thoroughly to make sure this doesn't change anything? Sometimes a linter can reformat and break things. I am careful on how much I lint my code, but if this isn't breaking or altering to the code base I am 100% a okay haha. Just wanted to touch base and make sure it was tested, since it changed lots of files.

**Comment by Keithw12** [comment]
> Have you tested thoroughly to make sure this doesn't change anything? Sometimes a linter can reformat and break things. I am careful on how much I lint my code, but if this isn't breaking or altering to the code base I am 100% a okay haha. Just wanted to touch base and make sure it was tested, since it changed lots of files.

I manually made those changes.  Nothing was auto changed.  99% of it was spacing, unnecessary semi-colins, and "" instead of '' quotes.

**Pull request merged**
